# Generated by Django 5.0.6 on 2024-06-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='deleted_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='deleted_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='deleted_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='deleted_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='deleted_at',
            new_name='updated_at',
        ),
    ]
